# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMr6DrLTDmJxxiP9iqhAN3056Zga7aqf
"""

from socket import *
import sys

# Create a TCP/IP socket
serverSocket = socket(AF_INET, SOCK_STREAM)

# Define the server address and port
serverAddress = ('localhost', 80)  # You can change 'localhost' to your server's IP address or domain name

# Bind the server socket to the address and port
serverSocket.bind(serverAddress)

# Listen for incoming connections
serverSocket.listen(1)

while True:
    # Wait for a connection
    print('Ready to serve...')
    connectionSocket, addr = serverSocket.accept()

    try:
        # Receive the HTTP request from the client
        message = connectionSocket.recv(1024).decode()

        # Extract the filename from the request
        filename = message.split()[1]

        # Open the requested file
        with open(filename[1:], 'rb') as f:
            # Read the content of the file
            outputdata = f.read()

        # Send HTTP response header
        responseHeader = "HTTP/1.1 200 OK\r\n\r\n"
        connectionSocket.send(responseHeader.encode())

        # Send the content of the requested file to the client
        connectionSocket.sendall(outputdata)

    except IOError:
        # If the file is not found, send a 404 Not Found response
        notFoundResponse = "HTTP/1.1 404 Not Found\r\n\r\n"
        connectionSocket.send(notFoundResponse.encode())

    finally:
        # Close the client connection
        connectionSocket.close()

# Close the server socket
serverSocket.close()